server:
  port: ${PORT:8081}
spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://andesstay-db.cmzs4nqytikw.us-east-1.rds.amazonaws.com:5432/andesstay}
    username: ${RESERVATIONS_DB_USER:postgres}
    password: ${RESERVATIONS_DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update # Solo demostracion
internal:
  token: ${INTERNAL_TOKEN:}
catalog:
  base-url: ${CATALOG_URL:http://localhost:8082}
